//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_UserProfile
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Prefix { get; set; }
        public string MobileNumber { get; set; }
        public string CountryCode { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string ProfilePic { get; set; }
        public string CitizenID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string StatusUser { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> StatusUnlock { get; set; }
        public string Role { get; set; }

        public string FullName{
            get{
                return Prefix + " " + FirstName + " " + LastName;
            }
        }
    }
}
