//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_Login
    {
        public int UserID { get; set; }
        public string PIN { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<bool> ActiveSession { get; set; }
        public string Password { get; set; }
        public string PendingOTP { get; set; }
    }
}
