//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_BillerCompany
    {
        public string ID { get; set; }
        public string ProductName { get; set; }
        public string AccountNumber { get; set; }
        public string CompanyPic { get; set; }
        public string Company { get; set; }
        public string Type { get; set; }
    }
}
