//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;

    public partial class GreenBank_Account
    {
        public string AccountNumber { get; set; }
        public int UserID { get; set; }
        public int AccountTypeID { get; set; }
        public string SerialNumber { get; set; }
        public string AccountStatus { get; set; }
        public string PassbookNumber { get; set; }


        public string AccountTypeName {
            get{

                switch (this.AccountTypeID)
                {
                    case 1:
                        return "Saving";
                    case 2:
                        return "Current";
                    case 3:
                        return "Fixed";
                    default:
                        return "Something";
                }
            }
        }
    }
}
