//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_Transaction
    {
        public string ReferenceNumber { get; set; }
        public int Sender { get; set; }
        public int Receiver { get; set; }
        public string SenderAccount { get; set; }
        public string ReceiverAccount { get; set; }
        public string SenderMobileNumber { get; set; }
        public string SenderCountryCode { get; set; }
        public string ReceiverMobileNumber { get; set; }
        public string ReceiverCountryCode { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public int Amount { get; set; }
        public int TransactionType { get; set; }
        public string Note { get; set; }
    }
}
