//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_Balance
    {
        public string AccountNumber { get; set; }
        public int AvailableBalance { get; set; }
        public string Currency { get; set; }
        public int UserID { get; set; }
    }
}
