//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnixerBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenBank_Merchant
    {
        public int MerchantID { get; set; }
        public string Address { get; set; }
        public string DisplayName { get; set; }
        public int RegistrationID { get; set; }
        public Nullable<int> AdminID { get; set; }
    }
}
